name: publish-to-medium
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Check out reposity
        uses: actions/checkout@v2
      - id: files
        uses: jitterbit/get-changed-files@v1
      - id: set-matrix
        name: Detecting posts from the changes
        run: |
          i=0
          file_list=()
          for changed_file in ${{ steps.files.outputs.added_modified }}; do
            echo "Do something with ${changed_file}."
            if [[ "${changed_file}" == "content/posts"* ]];
            then
              echo "File ${changed_file} matched post."
              file_list+=("$changed_file")
              ((i=i+1))
            fi
            echo "${file_list}."
          echo "::set-output name=matrix::{\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}"
  publish:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        files: ${{fromJson(needs.job1.outputs.matrix)}}
    steps:
      - run: echo ${{ matrix.files }}





      # - name: Publish to medium
      #   uses: infraway/post-medium-action@v1.6.0
      #   with:
      #     access_token: ${{ secrets.MEDIUM_ACCESS_TOKEN }}
      #     markdown_file: ${{ matrix.filepath }}
      #     base_url: https://myblog.com
      #     post_url: https://myblog.com/posts
     



        